namespace videocat
{
	[default_interface]
	unsealed runtimeclass BindableBase : Microsoft.UI.Xaml.DependencyObject, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
	{
		BindableBase();
		protected void RaisePropertyChanged(String propertyName);
	}
}
